name: "Master CI/CD"

run-name: "Master CI/CD runned by: ${{github.actor}}"

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, ready_for_review]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run the workflow on"
        required: true
        default: "main"
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - "warning"
          - "error"
          - "debug"

      tags:
        description: "Tags"
        required: false
        type: boolean

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: "First job"
        run: echo "My name is, ${{github.actor}}!"

      - name: "Values"
        run: echo "${{inputs.branch}} - ${{inputs.logLevel}} - ${{inputs.tags}} - ${{github.actor}}"
